Translated files Dutch language
e107inc/twofactorauth pull request #7
Opened 2023-12-11 19:05 UTC by Alex-e107nl

Dutch translation as currently used on e107.nl. Thank you Moc!!

2023-12-11 19:36 UTC, Moc commented
@Alex-e107nl Just one minor mistake, otherwise perfect! If you can fix it, that would be great, otherwise I'll do it after merging.

2023-12-11 19:53 UTC, Alex-e107nl commented
I would like to correct errors, but I don't see where you indicated which errors they are? I just search and search... tokens and emoticons that disappear on e107.nl and now here....

2023-12-11 19:56 UTC, Moc commented
If you check this page in your browser, you will see my comments: https://github.com/e107inc/twofactorauth/pull/7

2023-12-11 20:44 UTC, Alex-e107nl commented
Hihihi not really... i just get back on this page... #7 link does nothing for me... maybe you can do it please :-)

2023-12-11 20:52 UTC, Moc requested changes

2023-12-11 20:52 UTC, Moc commented on languages/Dutch/Dutch_front.php
> +define("LAN_2FA_VERIFY_INSTRUCTIONS", 		"Open de Twee Factor Authenticatie-app op uw apparaat om uw authenticatiecode te bekijken en uw identiteit te verifi&#235;ren.");
@Alex-e107nl This should be `verifiëren` rather than ` verifi&#235;ren`.  :)

2023-12-11 20:52 UTC, Moc commented on languages/Dutch/Dutch_front.php
> +define("LAN_2FA_DISABLED", 				"Tweefactorauthenticatie is succesvol [uitgeschakeld[/b]");
Check the [b] on "uitgeschakeld"

2023-12-11 20:52 UTC, Moc commented on languages/Dutch/Dutch_front.php
> +define("LAN_2FA_TITLE", "Two Factor Authentication");
This one can be translated as well :)

2023-12-11 20:52 UTC, Moc commented on languages/Dutch/Dutch_front.php
> +define("LAN_2FA_ENABLE_INSTRUCTIONS2", "Om te bevestigen dat uw authenticatie-app de juiste 6-cijferige code retourneert, verifieert u de code door deze hieronder in te voeren. Na verificatie wordt t
"Je" or "u"? You're using both, for consistency I would change this line to "je", so that you use "je" everywhere.

2023-12-11 20:53 UTC, Moc commented
@Alex-e107nl Sorry, that was my mistake. Now it should be visible :)

2023-12-11 21:15 UTC, Alex-e107nl commented
I think I have now sent the correct files, which is quite difficult for the first time.

2023-12-12 17:26 UTC, Moc approved these changes

2023-12-12 17:27 UTC, Moc commented
But you did it succesfully! Great job!

2023-12-12 17:27 UTC, merged